[package]
name = "billing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }

[dev-dependencies]
criterion = "0.4"
